import type { WebsiteFiles, WebsiteProject } from "./types";

export const WEBSITE_FIXED_FILES: Readonly<WebsiteFiles> = Object.freeze({
  "package.json": JSON.stringify({ name: "site-studio-site", version: "1.0.0", private: true, type: "module", scripts: { build: "tsc --noEmit && vite build" }, dependencies: { react: "19.2.4", "react-dom": "19.2.4" }, devDependencies: { "@types/react": "19.2.14", "@types/react-dom": "19.2.3", typescript: "5.9.3", vite: "6.4.1" } }, null, 2),
  "tsconfig.json": JSON.stringify({ compilerOptions: { target: "ES2022", lib: ["ES2022", "DOM", "DOM.Iterable"], module: "ESNext", moduleResolution: "Bundler", jsx: "react-jsx", strict: true, skipLibCheck: true, noEmit: true, allowImportingTsExtensions: true, resolveJsonModule: true }, include: ["src"] }, null, 2),
  "vite.config.ts": 'import { defineConfig } from "vite";\nexport default defineConfig({ base: "./", build: { outDir: "dist", sourcemap: false } });\n',
});

export function getStarterFiles(project?: WebsiteProject): WebsiteFiles {
  const context = project?.client_context ?? {};
  const whatsapp = (project?.cta.type === "whatsapp" ? project.cta.value : context.whatsapp ?? "").replace(/\D/g, "");
  const appUrl = (process.env.NEXT_PUBLIC_APP_URL ?? "").trim().replace(/\/+$/, "");
  const formEndpoint = project?.id && /^https?:\/\//i.test(appUrl) ? `${appUrl}/api/sites/forms/submit?project_id=${project.id}` : "";
  const data = { name: context.name || project?.name || "", description: context.description || "", services: context.services || "", address: context.address || "", phone: context.phone || "", whatsapp: /^\d{10,15}$/.test(whatsapp) ? whatsapp : "", projectId: project?.id || "", formEndpoint };
  return {
    ...WEBSITE_FIXED_FILES,
    "index.html": '<!doctype html>\n<html lang="pt-BR"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Contato</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>\n',
    "src/main.tsx": 'import { StrictMode } from "react";\nimport { createRoot } from "react-dom/client";\nimport App from "./App";\nimport "./tokens.css";\nimport "./styles.css";\ncreateRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);\n',
    "src/tokens.css": ':root{--color-bg:#090d16;--color-surface:#111827;--color-text:#f3f4f6;--color-text-muted:#9ca3af;--color-brand:#3b82f6;--color-brand-contrast:#ffffff;--color-border:#1f2937;--color-focus:#60a5fa;--font-body:system-ui,-apple-system,sans-serif;--font-display:var(--font-body);--size--1:.875rem;--size-0:1rem;--size-1:clamp(1.5rem,4vw,2.5rem);--size-2:clamp(2.5rem,8vw,5.5rem);--space-1:.75rem;--space-2:1.5rem;--radius:.5rem;--shadow:0 10px 25px -5px rgb(0 0 0 / .3)}\n',
    "src/content.json": JSON.stringify(data, null, 2),
    "src/App.tsx": 'import content from "./content.json";\nimport { ContactForm } from "./components/ContactForm";\nimport { WhatsAppButton } from "./components/WhatsAppButton";\n\nexport default function App() {\n  return <><header><a href="#inicio">{content.name || "Início"}</a><nav aria-label="Principal"><a href="#contato">Contato</a></nav></header><main id="inicio"><section className="hero"><h1>{content.name || "Entre em contato"}</h1>{content.description && <p>{content.description}</p>}<a className="button" href="#contato">Fale conosco</a></section>{content.services && <section aria-labelledby="servicos"><h2 id="servicos">Serviços</h2><p>{content.services}</p></section>}<section id="contato" aria-labelledby="titulo-contato"><h2 id="titulo-contato">Entre em contato</h2>{content.address && <p>{content.address}</p>}{content.phone && <p>{content.phone}</p>}<ContactForm endpoint={content.formEndpoint} /><WhatsAppButton phone={content.whatsapp} /></section></main><footer>{content.name}</footer></>;\n}\n',
    "src/components/WhatsAppButton.tsx": 'export function WhatsAppButton({ phone }: { phone: string }) {\n  const digits = phone.replace(/\\D/g, "");\n  if (!/^\\d{10,15}$/.test(digits)) return null;\n  return <a className="button whatsapp" href={`https://wa.me/${digits}`} target="_blank" rel="noopener noreferrer" aria-label="Conversar pelo WhatsApp">Conversar pelo WhatsApp</a>;\n}\n',
    "src/components/ContactForm.tsx": 'import { useState, type FormEvent } from "react";\n\nfunction newIdempotencyKey(): string {\n  const random = globalThis.crypto?.randomUUID?.();\n  return random ?? `key-${Date.now().toString(36)}-${(Math.random() + 1).toString(36).slice(2).padEnd(12, "0")}`;\n}\n\nexport function ContactForm({ endpoint }: { endpoint: string }) {\n  const [status, setStatus] = useState("");\n  const [busy, setBusy] = useState(false);\n  const [key, setKey] = useState("");\n  async function submit(event: FormEvent<HTMLFormElement>) {\n    event.preventDefault();\n    if (!endpoint || busy) return;\n    const form = event.currentTarget;\n    const fields = new FormData(form);\n    const idempotencyKey = key || newIdempotencyKey();\n    setKey(idempotencyKey);\n    setBusy(true);\n    setStatus("");\n    try {\n      const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...Object.fromEntries(fields), idempotency_key: idempotencyKey }) });\n      if (!response.ok) throw new Error("Falha no envio");\n      form.reset();\n      setKey("");\n      setStatus("Mensagem enviada.");\n    } catch {\n      setStatus("Não foi possível enviar. Tente novamente.");\n    } finally { setBusy(false); }\n  }\n  return <form onSubmit={submit}><label htmlFor="nome">Nome</label><input id="nome" name="name" autoComplete="name" required maxLength={120} minLength={2} /><label htmlFor="email">E-mail</label><input id="email" name="email" type="email" autoComplete="email" required maxLength={254} /><label htmlFor="mensagem">Mensagem</label><textarea id="mensagem" name="message" required maxLength={3000} /><label><input name="consent" type="checkbox" required value="true" />Autorizo o contato em resposta a esta mensagem.</label><button disabled={busy || !endpoint} type="submit">{busy ? "Enviando..." : "Enviar mensagem"}</button><p role="status">{status || (!endpoint ? "Formulário disponível após a publicação." : "")}</p></form>;\n}\n',
    "src/styles.css": ':root{font-family:var(--font-body);color:var(--color-text);background:var(--color-bg);font-synthesis:none;line-height:1.6}*{box-sizing:border-box}body{margin:0}header,main,footer{max-width:72rem;margin:auto;padding:1.5rem}header{display:flex;justify-content:space-between;gap:1rem;flex-wrap:wrap}a{color:inherit}section{padding:clamp(2rem,7vw,6rem) 0;border-bottom:1px solid var(--color-border)}.hero{max-width:56rem}h1{font-family:var(--font-display);font-size:var(--size-2);line-height:1.08;overflow-wrap:anywhere}h2{font-size:var(--size-1)}p{max-width:65ch;white-space:pre-line;color:var(--color-text-muted)}h1,h2{color:var(--color-text)}.button,button{display:inline-block;background:var(--color-brand);color:var(--color-brand-contrast);padding:.85rem 1.3rem;border:0;border-radius:var(--radius);font:inherit;text-decoration:none;cursor:pointer;min-height:44px}.whatsapp{margin-top:1rem}form{display:grid;gap:var(--space-1);max-width:34rem}input,textarea{font:inherit;max-width:100%;padding:.75rem;border:1px solid var(--color-border);border-radius:.3rem;background:var(--color-surface);color:var(--color-text)}textarea{min-height:8rem}input[type=checkbox]{min-width:1.25rem;min-height:1.25rem}button:disabled{opacity:.6;cursor:not-allowed}:focus-visible{outline:3px solid var(--color-focus);outline-offset:4px}img{max-width:100%;height:auto}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation:none!important;transition:none!important}}\n',
  };
}

export function getCleanStarterFiles(project?: WebsiteProject): WebsiteFiles {
  const context = project?.client_context ?? {};
  const name = context.name || project?.name || "Novo Site";
  return {
    ...WEBSITE_FIXED_FILES,
    "index.html": `<!doctype html>\n<html lang="pt-BR">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${name}</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>\n`,
    "src/main.tsx": 'import { StrictMode } from "react";\nimport { createRoot } from "react-dom/client";\nimport App from "./App";\nimport "./styles.css";\n\ncreateRoot(document.getElementById("root")!).render(\n  <StrictMode>\n    <App />\n  </StrictMode>\n);\n',
    "src/styles.css": ':root {\n  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;\n  line-height: 1.6;\n  font-synthesis: none;\n}\n*, *::before, *::after {\n  box-sizing: border-box;\n  margin: 0;\n  padding: 0;\n}\nbody {\n  min-height: 100vh;\n  -webkit-font-smoothing: antialiased;\n}\nbutton, input, textarea, select {\n  font: inherit;\n}\na {\n  color: inherit;\n  text-decoration: none;\n}\n',
    "src/App.tsx": `export default function App() {\n  return (\n    <main style={{ minHeight: "100vh", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "2rem", textAlign: "center", background: "#f8fafc", color: "#0f172a" }}>\n      <div style={{ maxWidth: "560px", padding: "2.5rem", borderRadius: "1rem", background: "#ffffff", boxShadow: "0 10px 25px -5px rgba(0,0,0,0.06)", border: "1px solid #e2e8f0" }}>\n        <span style={{ display: "inline-block", fontSize: "0.75rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", color: "#2563eb", marginBottom: "0.75rem" }}>Site Studio IA</span>\n        <h1 style={{ fontSize: "1.75rem", fontWeight: 800, marginBottom: "0.75rem", lineHeight: 1.2 }}>${name}</h1>\n        <p style={{ color: "#64748b", fontSize: "0.95rem", lineHeight: 1.6 }}>Preparando seu site...</p>\n      </div>\n    </main>\n  );\n}\n`,
  };
}
