export type InteractiveMessagePayload = any;

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  email?: string;
  company?: string;
  avatar_url?: string;
  remote_jid?: string;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  session_id?: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
  last_instance?: string;
  instance_name?: string | null;
  bot_status?: string;
  resume_at?: string | null;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
  filename?: string;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  match_type: 'exact' | 'contains';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================
